version: '3'
services:
  myapp:
    build: .
    volumes:
      - ./:/go/src/myapp
    ports:
      - "8080:8080"
    env_file: .env
    tty: true
  myapp-db:
    image: mysql:8.0
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
      - TZ='Asia/Tokyo'
    volumes:
      - ./Database/data:/var/lib/mysql
      - ./Database/my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - $MYSQL_PORT:3306

